name: "Pull Request Validation"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:

  quality-checks:
    uses: ./.github/workflows/_quality-checks.yaml

  build:
    needs: quality-checks
    uses: ./.github/workflows/_build.yaml
